// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// clk_out //
// ------- //

#define clk_out_wrap_target 0
#define clk_out_wrap 2
#define clk_out_pio_version 0

static const uint16_t clk_out_program_instructions[] = {
            //     .wrap_target
    0xb042, //  0: nop                    side 1
    0xa042, //  1: nop                    side 0
    0xa042, //  2: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program clk_out_program = {
    .instructions = clk_out_program_instructions,
    .length = 3,
    .origin = -1,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config clk_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + clk_out_wrap_target, offset + clk_out_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

