// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// syscfg_spi_tx //
// ------------- //

#define syscfg_spi_tx_wrap_target 0
#define syscfg_spi_tx_wrap 4
#define syscfg_spi_tx_pio_version 0

static const uint16_t syscfg_spi_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe027, //  1: set    x, 7
    0x7001, //  2: out    pins, 1         side 0
    0xb842, //  3: nop                    side 1
    0x1042, //  4: jmp    x--, 2          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program syscfg_spi_tx_program = {
    .instructions = syscfg_spi_tx_program_instructions,
    .length = 5,
    .origin = -1,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config syscfg_spi_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + syscfg_spi_tx_wrap_target, offset + syscfg_spi_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

